//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int ID_Equipos { get; set; }
        public string nombreEquipo { get; set; }
        public int entrenador { get; set; }
        public int primerPokemon { get; set; }
        public int segundoPokemon { get; set; }
        public int tercerPokemon { get; set; }
        public int cuartoPokemon { get; set; }
        public int quintoPokemon { get; set; }
        public int sextoPokemon { get; set; }
    
        public virtual Entrenadore Entrenadore { get; set; }
        public virtual Pokedex Pokedex { get; set; }
        public virtual Pokedex Pokedex1 { get; set; }
        public virtual Pokedex Pokedex2 { get; set; }
        public virtual Pokedex Pokedex3 { get; set; }
        public virtual Pokedex Pokedex4 { get; set; }
        public virtual Pokedex Pokedex5 { get; set; }
    }
}
